connect MihailBRZNT/MihailBRZNT@esigloca;
CREATE SYNONYM COMPTE
    FOR DrilonDMR.COMPTE;

CREATE SYNONYM TYPE_COMPTE
    FOR DrilonDMR.TYPE_COMPTE;
      
CREATE SYNONYM REVENU
    FOR DrilonDMR.TYPE_COMPTE;  

CREATE SYNONYM REVENU
    FOR RomainCMPNH.REVENU;  

CREATE SYNONYM CATEGORIE_REVENU
    FOR RomainCMPNH.CATEGORIE_REVENU;  

CREATE SYNONYM DEPENSE
    FOR KarimELMZR.DEPENSE;  

CREATE SYNONYM ABONNEMENT
    FOR KarimELMZR.ABONNEMENT;  

CREATE SYNONYM CATEGORIE_REVENU
    FOR KarimELMZR.CATEGORIE_REVENU;  
DISCONNECT;



connect DrilonDMR/DrilonDMR@esigloca;
CREATE SYNONYM CLIENT
    FOR MihailBRZNT.CLIENT;

CREATE SYNONYM OBJECTIF
    FOR MihailBRZNT.OBJECTIF;
      
CREATE SYNONYM DEPENSE
    FOR KarimELMZR.DEPENSE;  

CREATE SYNONYM ABONNEMENT
    FOR KarimELMZR.ABONNEMENT;  

CREATE SYNONYM CATEGORIE_REVENU
    FOR KarimELMZR.CATEGORIE_REVENU;  

CREATE SYNONYM REVENU
    FOR RomainCMPNH.REVENU;  

CREATE SYNONYM CATEGORIE_REVENU
    FOR RomainCMPNH.CATEGORIE_REVENU;  

DISCONNECT;


connect KarimELMZR/KarimELMZR@esigloca;
CREATE SYNONYM CLIENT
    FOR MihailBRZNT.CLIENT;

CREATE SYNONYM OBJECTIF
    FOR MihailBRZNT.OBJECTIF;
      
CREATE SYNONYM COMPTE
    FOR DrilonDMR.COMPTE;

CREATE SYNONYM TYPE_COMPTE
    FOR DrilonDMR.TYPE_COMPTE;

CREATE SYNONYM REVENU
    FOR RomainCMPNH.REVENU;  

CREATE SYNONYM CATEGORIE_REVENU
    FOR RomainCMPNH.CATEGORIE_REVENU;  


DISCONNECT;

connect RomainCMPNH/RomainCMPNH@esigloca;
CREATE SYNONYM CLIENT
    FOR MihailBRZNT.CLIENT;

CREATE SYNONYM OBJECTIF
    FOR MihailBRZNT.OBJECTIF;

CREATE SYNONYM COMPTE
    FOR DrilonDMR.COMPTE;

CREATE SYNONYM TYPE_COMPTE
    FOR DrilonDMR.TYPE_COMPTE;

CREATE SYNONYM DEPENSE
    FOR KarimELMZR.DEPENSE;  

CREATE SYNONYM ABONNEMENT
    FOR KarimELMZR.ABONNEMENT;  

CREATE SYNONYM CATEGORIE_REVENU
    FOR KarimELMZR.CATEGORIE_REVENU;  

DISCONNECT;
EXIT;	
