-- USER SQL

CREATE USER DrilonDMR IDENTIFIED BY "DrilonDMR"  
DEFAULT TABLESPACE MKRD_TS
TEMPORARY TABLESPACE MKRD_TEMP;
PROFILE "DevProfile";

CREATE USER MihailBRZNT IDENTIFIED BY "MihailBRZNT"  
DEFAULT TABLESPACE MKRD_TS
TEMPORARY TABLESPACE MKRD_TEMP;
PROFILE "DevProfile";

CREATE USER KarimELMZR IDENTIFIED BY "KarimELMZR"  
DEFAULT TABLESPACE MKRD_TS
TEMPORARY TABLESPACE MKRD_TEMP;
PROFILE "DevProfile";

CREATE USER RomainCMPNH IDENTIFIED BY "RomainCMPNH" 
DEFAULT TABLESPACE MKRD_TS
TEMPORARY TABLESPACE MKRD_TEMP;
PROFILE "DevProfile";

-- QUOTAS

ALTER USER DrilonDMR QUOTA UNLIMITED ON MKRD_TS;

ALTER USER MihailBRZNT QUOTA UNLIMITED ON MKRD_TS;

ALTER USER KarimELMZR QUOTA UNLIMITED ON MKRD_TS;

ALTER USER RomainCMPNH QUOTA UNLIMITED ON MKRD_TS;

-- ROLES

GRANT "DEVELOPPEUR" TO DrilonDMR ;
GRANT RESOURCE TO DrilonDMR ;

GRANT "DEVELOPPEUR"  TO MihailBRZNT ;
GRANT RESOURCE TO MihailBRZNT ;

GRANT "DEVELOPPEUR"  TO KarimELMZR ;
GRANT RESOURCE TO KarimELMZR ;

GRANT "DEVELOPPEUR"  TO RomainCMPNH ;
GRANT RESOURCE TO RomainCMPNH ;

-- SYSTEM PRIVILEGES

EXIT;