CREATE PROFILE "Profile_Developpeur" LIMIT
CPU_PER_SESSION DEFAULT
CPU_PER_CALL DEFAULT
CONNECT_TIME UNLIMITED
IDLE_TIME 120
SESSIONS_PER_USER 2
LOGICAL_READS_PER_SESSION DEFAULT
LOGICAL_READS_PER_CALL DEFAULT
PRIVATE_SGA DEFAULT
COMPOSITE_LIMIT DEFAULT
PASSWORD_LIFE_TIME 90
PASSWORD_GRACE_TIME DEFAULT
PASSWORD_REUSE_MAX DEFAULT
PASSWORD_REUSE_TIME DEFAULT
PASSWORD_VERIFY_FUNCTION DEFAULT
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 10/1440;



CREATE PROFILE "Profile_Utilisateur_Final" LIMIT
CPU_PER_SESSION DEFAULT
CPU_PER_CALL DEFAULT
CONNECT_TIME DEFAULT
IDLE_TIME 60
SESSIONS_PER_USER 2
LOGICAL_READS_PER_SESSION DEFAULT
LOGICAL_READS_PER_CALL DEFAULT 
PRIVATE_SGA DEFAULT
COMPOSITE_LIMIT DEFAULT
PASSWORD_LIFE_TIME 90
PASSWORD_GRACE_TIME DEFAULT 
PASSWORD_REUSE_MAX DEFAULT
PASSWORD_REUSE_TIME DEFAULT
PASSWORD_VERIFY_FUNCTION DEFAULT
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LOCK_TIME DEFAULT; 

CREATE PROFILE "Profile_DBA" LIMIT
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL UNLIMITED
CONNECT_TIME 480
IDLE_TIME 5
SESSIONS_PER_USER 3
PASSWORD_LIFE_TIME 60
PASSWORD_GRACE_TIME UNLIMITED 
PASSWORD_REUSE_MAX 1
PASSWORD_REUSE_TIME 1
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 1; 

EXIT;