-- USER SQL
CREATE USER ViewUSER IDENTIFIED BY ViewUSER  
DEFAULT TABLESPACE MKRD_TS
TEMPORARY TABLESPACE MKRD_TEMP;


CREATE USER DrilonDMR IDENTIFIED BY DrilonDMR  
DEFAULT TABLESPACE MKRD_TS
TEMPORARY TABLESPACE MKRD_TEMP;

CREATE USER MihailBRZNT IDENTIFIED BY MihailBRZNT  
DEFAULT TABLESPACE MKRD_TS
TEMPORARY TABLESPACE MKRD_TEMP;

CREATE USER KarimELMZR IDENTIFIED BY KarimELMZR  
DEFAULT TABLESPACE MKRD_TS
TEMPORARY TABLESPACE MKRD_TEMP;

CREATE USER RomainCMPNH IDENTIFIED BY RomainCMPNH  
DEFAULT TABLESPACE MKRD_TS
TEMPORARY TABLESPACE MKRD_TEMP;

-- QUOTAS

ALTER USER DrilonDMR QUOTA UNLIMITED ON MKRD_TS;

ALTER USER MihailBRZNT QUOTA UNLIMITED ON MKRD_TS;

ALTER USER KarimELMZR QUOTA UNLIMITED ON MKRD_TS;

ALTER USER RomainCMPNH QUOTA UNLIMITED ON MKRD_TS;

-- ROLES
GRANT CONNECT TO ViewUSER ;
GRANT CREATE VIEW TO ViewUSER;

GRANT CONNECT TO DrilonDMR ;
GRANT RESOURCE TO DrilonDMR ;

GRANT CONNECT TO MihailBRZNT ;
GRANT RESOURCE TO MihailBRZNT ;

GRANT CONNECT TO KarimELMZR ;
GRANT RESOURCE TO KarimELMZR ;

GRANT CONNECT TO RomainCMPNH ;
GRANT RESOURCE TO RomainCMPNH ;

-- SYSTEM PRIVILEGES

